import io
import re
import fitz
from typing import List, Dict, Any, Tuple
from src.config import PAGE_W, PAGE_H, MARGIN, TW

def _strip_md(text: str) -> str:
    """Strip basic markdown formatting syntax for clean PDF text insertion."""
    text = re.sub(r'^#{1,4}\s+', '', text, flags=re.MULTILINE)
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'`(.*?)`', r'\1', text)
    return text.strip()

class PageWriter:
    """Helper that writes formatted text and layouts to PyMuPDF pages with auto page-break."""
    def __init__(self, doc):
        self.doc = doc
        self.page = None
        self.y = 0
        self._new_page()

    def _new_page(self):
        self.page = self.doc.new_page(width=PAGE_W, height=PAGE_H)
        self.y = MARGIN + 10

    def _ensure_space(self, needed: float = 20):
        if self.y + needed > PAGE_H - MARGIN:
            self._new_page()

    def write_line(self, text: str, fontsize: int = 10, bold: bool = False,
                   color: Tuple[float, float, float] = (0, 0, 0), indent: int = 0):
        self._ensure_space(fontsize + 6)
        fn = "hebo" if bold else "helv"
        self.page.insert_text(
            (MARGIN + indent, self.y), text,
            fontsize=fontsize, fontname=fn, color=color
        )
        self.y += fontsize + 5

    def write_wrapped(self, text: str, fontsize: int = 10, bold: bool = False,
                      color: Tuple[float, float, float] = (0.1, 0.1, 0.1),
                      indent: int = 0, line_h: int = 15):
        fn = "hebo" if bold else "helv"
        cpl = max(1, int((TW - indent) / (fontsize * 0.52)))
        words = text.split()
        line = ""
        for w in words:
            test = (line + " " + w).strip()
            if len(test) > cpl:
                self._ensure_space(line_h)
                self.page.insert_text(
                    (MARGIN + indent, self.y), line,
                    fontsize=fontsize, fontname=fn, color=color
                )
                self.y += line_h
                line = w
            else:
                line = test
        if line:
            self._ensure_space(line_h)
            self.page.insert_text(
                (MARGIN + indent, self.y), line,
                fontsize=fontsize, fontname=fn, color=color
            )
            self.y += line_h

    def write_divider(self, color: Tuple[float, float, float] = (0.7, 0.7, 0.8)):
        self._ensure_space(10)
        self.page.draw_line((MARGIN, self.y), (PAGE_W - MARGIN, self.y), color=color, width=0.5)
        self.y += 8

    def write_section_heading(self, text: str, color: Tuple[float, float, float] = (0.2, 0.3, 0.75)):
        self.y += 8
        self._ensure_space(30)
        self.write_line(text, fontsize=12, bold=True, color=color)
        self.write_divider()

    def write_markdown_block(self, md_text: str, fontsize: int = 10):
        """Render markdown text block with headings, bullets, and wrapped paragraphs."""
        for raw in md_text.split('\n'):
            raw = raw.rstrip()
            if not raw:
                self.y += 5
                continue
            if re.match(r'^#{1,4} ', raw):
                text = re.sub(r'^#{1,4} ', '', raw)
                self.write_line(_strip_md(text), fontsize=fontsize + 1, bold=True, color=(0.15, 0.25, 0.65))
                self.y += 2
            elif re.match(r'^[\-\*\+] ', raw.strip()):
                text = "•  " + _strip_md(raw.strip()[2:])
                self.write_wrapped(text, fontsize=fontsize, color=(0.1, 0.1, 0.1), indent=8)
            elif re.match(r'^\d+\. ', raw.strip()):
                self.write_wrapped(_strip_md(raw.strip()), fontsize=fontsize, color=(0.1, 0.1, 0.1), indent=8)
            else:
                self.write_wrapped(_strip_md(raw), fontsize=fontsize, color=(0.15, 0.15, 0.15))

    def cover_page(self, title: str, subtitle: str, topic: str):
        """Write a styled divider cover page."""
        self._new_page()
        self.page.draw_rect(fitz.Rect(0, 0, PAGE_W, 6), color=(0.2, 0.3, 0.75), fill=(0.2, 0.3, 0.75))
        self.y = PAGE_H // 3
        self.write_line(title, fontsize=20, bold=True, color=(0.2, 0.3, 0.75), indent=(TW - len(title) * 11) // 2)
        self.y += 6
        self.write_divider(color=(0.2, 0.3, 0.75))
        self.write_wrapped(subtitle, fontsize=11, color=(0.4, 0.4, 0.4))
        if topic:
            self.y += 8
            self.write_wrapped(f"Topic: {topic}", fontsize=10, color=(0.5, 0.5, 0.5))
        self.write_line("Generated by ScholarAI via Groq + LangGraph", fontsize=8, color=(0.6, 0.6, 0.6))
        self.page.draw_rect(fitz.Rect(0, PAGE_H - 6, PAGE_W, PAGE_H), color=(0.2, 0.3, 0.75), fill=(0.2, 0.3, 0.75))

def apply_edits_to_pdf(orig_doc: fitz.Document, edits: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Apply in-place text replacement to PDF pages using redaction annotations.
    
    Returns a list of successfully applied edit descriptors.
    """
    applied_edits = []
    for edit in edits:
        original_snip = edit.get("original", "").strip()
        rewritten = edit.get("rewritten", "").strip()
        section = edit.get("section", "")
        if not original_snip or not rewritten:
            continue

        found = False
        for key_len in [120, 80, 50, 30]:
            search_key = original_snip[:key_len].strip()
            if not search_key:
                continue
            for page in orig_doc:
                hits = page.search_for(search_key)
                if not hits:
                    continue
                rect = hits[0]
                line_count = max(3, len(original_snip) // 70)
                rep_rect = fitz.Rect(
                    rect.x0 - 1,
                    rect.y0 - 2,
                    page.rect.width - MARGIN + 10,
                    rect.y0 + line_count * 13 + 10
                ) & page.rect

                # Redact original text
                page.add_redact_annot(rep_rect, fill=(1, 1, 1))
                page.apply_redactions()

                # Insert rewritten text
                fs = 10
                x, y = rep_rect.x0 + 1, rep_rect.y0 + fs + 1
                max_chars = max(1, int(rep_rect.width / (fs * 0.52)))
                words = rewritten.split()
                line = ""
                for w in words:
                    test = (line + " " + w).strip()
                    if len(test) > max_chars:
                        if y + fs < rep_rect.y1:
                            page.insert_text((x, y), line, fontsize=fs, fontname="helv", color=(0, 0, 0))
                            y += fs + 3
                        line = w
                    else:
                        line = test
                if line and y + fs < rep_rect.y1:
                    page.insert_text((x, y), line, fontsize=fs, fontname="helv", color=(0, 0, 0))

                applied_edits.append({"section": section, "rewritten": rewritten})
                found = True
                break
            if found:
                break
    return applied_edits

def build_edited_original_pdf(original_pdf_path: str, edits: List[Dict[str, Any]]) -> io.BytesIO:
    """Produce PDF with only in-place edits applied to the original document."""
    orig = fitz.open(original_pdf_path)
    apply_edits_to_pdf(orig, edits)
    buf = io.BytesIO()
    orig.save(buf, garbage=4, deflate=True)
    orig.close()
    buf.seek(0)
    return buf

def build_analysis_pdf(original_pdf_path: str, summary: str, vision: list,
                       comparison: str, improvements: str, edits: list,
                       papers: list, topic: str, qa_text: str = "") -> io.BytesIO:
    """Build complete analysis PDF: original edited paper + 4 structured appendix sections."""
    orig = fitz.open(original_pdf_path)
    applied_edits = apply_edits_to_pdf(orig, edits)

    analysis = fitz.open()
    pw = PageWriter(analysis)

    # Section 1: Summary & Figures
    pw.cover_page("SECTION 1 — PAPER SUMMARY", "AI-generated structured summary of the uploaded paper", topic)
    pw._new_page()
    pw.write_section_heading("Paper Summary")
    pw.write_markdown_block(summary)

    if vision:
        pw.write_section_heading("Figure Analysis")
        for i, v in enumerate(vision):
            pw.write_line(f"Figure {i + 1}", fontsize=10, bold=True, color=(0.8, 0.5, 0.1))
            pw.write_markdown_block(v)
            pw.y += 6

    # Section 2: Q&A
    pw.cover_page("SECTION 2 — Q&A", "Questions and answers from the interactive session", topic)
    pw._new_page()
    pw.write_section_heading("Q&A Session")
    if qa_text:
        for block in qa_text.split("---"):
            block = block.strip()
            if not block:
                continue
            lines = block.split("\n\n", 1)
            q_line = lines[0].replace("Q: ", "").strip() if lines else ""
            a_text = lines[1].replace("A: ", "").strip() if len(lines) > 1 else ""
            pw.write_line(f"Q: {q_line}", fontsize=10, bold=True, color=(0.9, 0.6, 0.1))
            pw.y += 2
            pw.write_markdown_block(a_text)
            pw.y += 8
    else:
        pw.write_wrapped("No questions were asked during this session.", fontsize=10, color=(0.4, 0.4, 0.4))

    # Section 3: Comparative Study
    pw.cover_page("SECTION 3 — COMPARATIVE STUDY", "Comparison with recent academic literature", topic)
    pw._new_page()
    pw.write_section_heading("Related Papers Found")
    for p in papers:
        venue_str = f" ({p['venue']})" if p.get("venue") else ""
        pw.write_line(f"[{p.get('year', 'N/A')}] {p.get('title', 'Untitled')}{venue_str}",
                      fontsize=9, bold=True, color=(0.2, 0.3, 0.7))
        pw.write_wrapped(p.get('summary', '')[:300], fontsize=9, color=(0.4, 0.4, 0.4))
        pw.y += 4

    pw.write_section_heading("Comparative Analysis")
    pw.write_markdown_block(comparison)

    # Section 4: Improvements & Rewrites
    pw.cover_page("SECTION 4 — IMPROVEMENTS & REWRITES", "AI-identified weak sections and their rewritten versions", topic)
    pw._new_page()
    pw.write_section_heading("Improvement Analysis")
    pw.write_markdown_block(improvements)

    if applied_edits:
        pw.write_section_heading("Rewritten Sections (applied to paper)")
        for ed in applied_edits:
            pw.write_line(f"Section: {ed['section']}", fontsize=10, bold=True, color=(0.1, 0.5, 0.3))
            pw.write_markdown_block(ed['rewritten'])
            pw.y += 8
    else:
        pw.write_wrapped(
            "Note: Automatic in-place replacement could not locate exact text snippets "
            "in the PDF (e.g. scanned or complex multi-column PDFs). "
            "The rewritten sections are presented below for manual reference.",
            fontsize=10, color=(0.7, 0.4, 0.1)
        )
        pw.y += 8
        for ed in edits:
            if ed.get("rewritten"):
                pw.write_line(f"Section: {ed.get('section', '')}", fontsize=10, bold=True, color=(0.1, 0.5, 0.3))
                pw.write_markdown_block(ed["rewritten"])
                pw.y += 8

    # Merge original (edited) + analysis
    orig.insert_pdf(analysis)
    buf = io.BytesIO()
    orig.save(buf, garbage=4, deflate=True)
    orig.close()
    analysis.close()
    buf.seek(0)
    return buf
